### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by DataExplorerUser** [datoviz/datoviz#30]
Win 10, Python 3.8 running in a fresh venv with numpy and datoviz. Pip installed the windows wheels of v.0.1.0. Using PyCharm as IDE.

Running the following example code from the Datoviz website, resulted in an error.

```Python
import numpy as np
from datoviz import canvas, run, colormap

panel = canvas(show_fps=True).scene().panel()
visual = panel.visual('marker')

N = 10_000
pos = np.random.randn(N, 3)
ms = np.random.uniform(low=2, high=35, size=N)
color = colormap(np.random.rand(N), cmap='viridis')

visual.data('pos', pos)
visual.data('ms', ms)
visual.data('color', color)

run()
```

Error shown.
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/build

```
Traceback (most recent call last):
  File "C:\Users\USER1\PycharmProjects\DatoViz_1\venv\lib\site-packages\datoviz\__init__.py", line 14, in <module>
    from .pydatoviz import App, colormap, demo
ImportError: DLL load failed while importing pydatoviz: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/USER1/PycharmProjects/DatoViz_1/main.py", line 2, in <module>
    from datoviz import canvas, run, colormap
  File "C:\Users\USER1\PycharmProjects\DatoViz_1\venv\lib\site-packages\datoviz\__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to load the shared library, make sure to run in your terminal:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/build`

Process finished with exit code 1
```

**Comment by rossant** [comment]
What is your GPU model and GPU driver version?
Can you determine if you have a `libvulkan.dll` file in your system files?

**Comment by DataExplorerUser** [comment]
I wouldn't know where to locate libvulkan.dll, so I searched the C drive with explorer. No items found. Any specific location I should check?

**Comment by rossant** [comment]
Your hardware might not support Vulkan. If you install https://www.techpowerup.com/gpuz/, it might tell you whether you GPU chip supports Vulkan.

**Comment by oren-weiss** [comment]
Just to bump this: my computer has a Intel UHD 620 card, which according to the link above, has Vulkan available. Moreover,
when installing the prebuilt wheel in a python virtualenv works fine, but when I try to build the library from source (Windows 11), I get the same error:

```
Traceback (most recent call last):
  File "c:\users\USER_NAME\datoviz\bindings\cython\datoviz\__init__.py", line 14, in <module>
    from .pydatoviz import App, colormap, colorpal, demo
ImportError: DLL load failed while importing pydatoviz: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER_NAME\datoviz\bindings\cython\examples\quickstart.py", line 12, in <module>
    from datoviz import canvas, run, colormap
  File "c:\users\USER_NAME\datoviz\bindings\cython\datoviz\__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to load the shared library, make sure to run in your terminal:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/build`
```

Additionally, when building on Windows, fyi you need to use `python setup.py build_ext -i -c mingw --inplace -DMS_WIN64`

**Comment by rossant** [comment]
Closing since this concerns an old version.
