### ISSUE TITLE
The Usage example from README fails: TypeError: 'DVZ' object is not callable

### ISSUE THREAD

**Issue by yurivict** [datoviz/datoviz#65]
```
$ python3.11 x.py 
Error loading /usr/local/lib/python3.11/site-packages/datoviz: /usr/local/lib/python3.11/site-packages/datoviz: read error: Invalid argument
Traceback (most recent call last):
  File "/usr/ports/science/py-datoviz/x.py", line 4, in <module>
    app = dvz.app(0)
          ^^^^^^^^^^
TypeError: 'DVZ' object is not callable
[yuri@yv /usr/ports/science/py-datoviz]$ python3.11 x.py 
Error loading /usr/local/lib/python3.11/site-packages/datoviz: /usr/local/lib/python3.11/site-packages/datoviz: read error: Invalid argument
Traceback (most recent call last):
  File "/usr/ports/science/py-datoviz/x.py", line 4, in <module>
    app = dvz.app(0)
          ^^^^^^^^^^
TypeError: 'DVZ' object is not callable
```

Version: 0.2.1
FreeBSD 14.1

**Comment by rossant** [comment]
I've never tested Datoviz on FreeBSD. I don't know if an arbitrary Linux library that was compiled, say, on AlmaLinux (like the library shipped with the Linux Python wheel), is expected to work as is on FreeBSD? In any case, you might want to try building Datoviz from scratch. Here's a starting point: https://github.com/datoviz/datoviz/blob/main/BUILD.md#ubuntu-2404

**Comment by yurivict** [comment]
I've built it from scratch, and the above error is what I got.

**Comment by yurivict** [comment]
I've built the Python library.
It installed only these files:
```
        /usr/local/lib/python3.11/site-packages/datoviz/__init__.py
        /usr/local/lib/python3.11/site-packages/datoviz/__pycache__/__init__.cpython-311.opt-1.pyc
        /usr/local/lib/python3.11/site-packages/datoviz/__pycache__/__init__.cpython-311.pyc
```

It looks like these files aren't sufficient, but PEP517 build and install modules installed only them for some reason.

**Comment by rossant** [comment]
The error message you're encountering is not related to the Python library but to the underlying compiled C library `libdatoviz.so` which doesn't seem to load properly on your system. I'd suggest compiling this C library, without bothering about Python for now (which only provides a thin ctypes wrapper on top of this C library).

You essentially have to do `just build || just build` after you've installed the build requirements.

**Comment by rossant** [comment]
Thanks for reporting this. The original issue was about Datoviz v0.2.1, but the build system has been completely redesigned for v0.4.

We’ve added initial instructions for building Datoviz from source on FreeBSD 14 amd64: [FreeBSD build instructions](https://github.com/datoviz/datoviz/blob/v0.4-dev/docs/start/build-from-source.md#freebsd-14-amd64).

Could you try them on the current `v0.4-dev` branch and let us know what works or fails? Please include the diagnostics listed in the guide.

For now, FreeBSD is a community-tested source-build target: we do not provide binaries or wheels, and it is not yet part of our release CI. Your results will help us fix portability issues and turn these initial instructions into a verified guide.

**Comment by rossant** [comment]
The build and API have changed substantially since the original v0.2.1 report. Current `main` now includes provisional FreeBSD source-build instructions:

https://github.com/datoviz/datoviz/blob/main/docs/start/build-from-source.md

Could you retry with current `main` and report the complete CMake configure/build output, compiler version, Vulkan SDK/loader details, and the first failing command?

FreeBSD is currently treated as a community-tested source-build target. We do not yet claim FreeBSD wheels, release CI, Python-package support, or inclusion in the RC3 release matrix. I’ll keep this open for current portability findings.
