### ISSUE TITLE
pip install -e . does not work?

### ISSUE THREAD

**Issue by m-beau** [datoviz/datoviz#70]
MWE:
```
git clone git clone https://github.com/datoviz/datoviz.git
cd datoviz
pip install -e .
python
>>> import datoviz
```

Error log:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/maxime/ut_data/Dropbox/Science/datoviz/datoviz/__init__.py", line 68, in <module>
    raise RuntimeError(f"Unable to find `{LIB_PATH}`.")
RuntimeError: Unable to find `/media/maxime/ut_data/Dropbox/Science/datoviz/build/libdatoviz.so`.
```
Cheers

**Comment by rossant** [comment]
Yes, pip installing the GitHub version does not suffice because the Python bindings require the compiled shared library (.so/.dylib/.dll). Try following the instructions here instead: https://github.com/datoviz/datoviz/blob/main/BUILD.md

**Comment by m-beau** [comment]
All right! Thanks.
